#!/bin/bash

url=$1
startfolder=$(pwd)
repo_install_path="/bin/filter-repo"
zpool="zfs"

export PATH="$PATH:${repo_install_path}"

now=$(date +"%b %d %Y")
name=$(echo "$url" | md5sum | cut -d" " -f1)

# Naive
mkdir "$name"
cd "$name"
git clone "$url" "$now"
cd "$now"

git filter-repo --path-regex '^.*.java$' --force
git remote add origin "$url"

# Efficient
zfs create "${zpool}/${name}"
cd "/${zpool}/${name}"
git clone "$url" .

git filter-repo --path-regex '^.*.java$' --force
git remote add origin "$url"

cd .git
mv objects/pack pack
pack=$(ls pack | grep '.pack')
git unpack-objects < pack/"$pack"
rm -rf pack
cd ../

zfs snapshot -r "${zpool}/${name}@${now}"
